// export const creativeProjects = [
//   {
//     name: 'DevDash',
//     kind: 'SaaS Dashboard',
//     stack: ['React', 'TypeScript', 'Charts'],
//     color: '#d9a62e',
//     symbol: 'DD',
//     description: 'Clear product signals inside a focused analytics command center.',
//   },
//   {
//     name: 'API Forge',
//     kind: 'Backend / API Tool',
//     stack: ['Node', 'REST', 'Postgres'],
//     color: '#78804c',
//     symbol: 'AF',
//     description: 'Compose, test, and monitor dependable API workflows visually.',
//   },
//   {
//     name: 'MotionLab',
//     kind: 'Interactive UI',
//     stack: ['React', 'Canvas', 'Motion'],
//     color: '#b97732',
//     symbol: 'ML',
//     description: 'Playful interface experiments driven by motion and physics.',
//   },
//   {
//     name: 'CodeCanvas',
//     kind: 'Creative Portfolio',
//     stack: ['Vite', 'CSS', 'UX'],
//     color: '#aa842d',
//     symbol: 'CC',
//     description: 'A visual identity system shaped into an explorable web story.',
//   },
//   {
//     name: 'Task Orbit',
//     kind: 'Productivity App',
//     stack: ['Next.js', 'Firebase', 'PWA'],
//     color: '#626c43',
//     symbol: 'TO',
//     description: 'A tactile planner that turns scattered ideas into momentum.',
//   },
// ]
