export const projects = [
  {
    id: '01',
    name: 'SalesPro',
    type: 'Sales Management Dashboard',
    category: 'React',
    desc: 'A modern analytics dashboard designed to transform complex business data into clear insights through interactive charts, performance metrics, and intuitive reporting.',
    tech: ['React', 'TypeScript', 'Charts'],
    status: 'stable',
    color: '#a9c7d0',
    link: 'https://sales-pro-zeta.vercel.app/',
    image: '/thumbnails/SalesPro.png',
    repo: 'https://github.com/CodyAHS02/SalesPro',
  },
  {
    id: '02',
    name: 'Mex Sabor',
    type: 'Restaurant',
    category: 'CMS',
    desc: 'A modern restaurant website featuring an elegant dining experience, immersive visuals, intuitive navigation, and seamless online reservations.',
    tech: ['Wordpress', 'Elementor'],
    status: 'stable',
    color: '#e7a271',
    link: 'hhttps://mexsabor.online/',
    image: '/thumbnails/mexsabor.png',
  },
  {
    id: '03',
    name: 'Spill The Tea',
    type: 'Social Platform',
    category: 'Full Stack Web App',
    desc: 'A modern social networking platform designed for real-time conversations, content sharing, and meaningful community engagement.',
    tech: ['React Vite', 'Supabase'],
    status: 'stable',
    color: '#a8bb8a',
    link: 'https://spill-the-tea-beta-six.vercel.app/',
    image: '/thumbnails/spill-the-tea.png',
    repo: 'https://github.com/CodyAHS02/spill-the-tea',
  },
  {
    id: '04',
    name: '9toFit',
    type: 'Fitness',
    category: 'CMS',
    desc: 'A modern fitness platform designed to inspire healthier lifestyles through an engaging user experience, responsive design, and seamless navigation.',
    tech: ['Wordpress', 'Elementor'],
    status: 'stable',
    color: '#a8bb8a',
    link: 'https://9tofit.nl',
    image: '/thumbnails/9tofit.png',
  },
  {
    id: '05',
    name: 'Dentora Clinic',
    type: 'Clinic',
    category: 'Front-end',
    desc: 'A modern dental clinic website designed to showcase services, simplify appointment booking, and provide a seamless patient experience.',
    tech: ['Next JS', 'CSS'],
    status: 'stable',
    color: '#e8ce72',
    link: 'https://dentora-clinic-mu.vercel.app/',
    image: '/thumbnails/dentora.png',
    repo: 'https://github.com/CodyAHS02/Dentora-Clinic',
  },
  {
    id: '06',
    name: 'loopy lamb Crochet',
    type: 'E-commerce',
    category: 'CMS',
    desc: 'A charming handmade crafts website showcasing unique crochet creations with an elegant shopping experience and visually engaging design.',
    tech: ['Wordpress', 'Elementor', 'WooCommerce'],
    status: 'stable',
    color: '#e58972',
    link: 'https://theloopylambcrochet.com',
    image: '/thumbnails/loopylamb.png',
  },
  {
    id: '07',
    name: 'TubeMaster',
    type: 'Web App',
    category: 'Front-end + API',
    desc: 'A YouTube-inspired web application that fetches real-time video content through API integration, offering a familiar and responsive browsing experience.',
    tech: ['React Vite', 'Tailwind CSS', 'RapidAPI'],
    status: 'stable',
    color: '#c2afd1',
    link: 'http://watch-tube-master.vercel.app/',
    image: '/thumbnails/tube-master-thumbnail.jpg',
    repo: 'https://github.com/CodyAHS02/watchTube-master',
  },
  {
    id: '08',
    name: 'AI Revolution Programme',
    type: 'Programme',
    category: 'UI',
    desc: 'A modern AI-focused website featuring a sleek design, streamlined appointment scheduling, and intuitive inquiry forms for a seamless user experience.',
    tech: ['Next JS', 'CSS'],
    status: 'stable',
    color: '#c2afd1',
    link: 'https://ai-revolution-programme.vercel.app/',
    image: '/thumbnails/ai-revolution-programme.png',
    repo: 'https://github.com/CodyAHS02/AI-Revolution-Programme',
  },
  {
    id: '09',
    name: 'Jess L. Jackson',
    type: 'Author Website',
    category: 'Landing Page',
    desc: "A modern author website designed to showcase books, share the author's journey, and provide readers with an engaging and seamless browsing experience.",
    tech: ['Wordpress', 'Elementor'],
    status: 'stable',
    color: '#c2afd1',
    link: 'https://jessljackson.com/',
    image: '/thumbnails/jessica.png',
  },
  {
    id: '10',
    name: 'BlueOceans',
    type: 'Coroporate',
    category: 'Consultation',
    desc: 'A modern corporate website designed to showcase business services, strengthen brand presence, and deliver a professional user experience.',
    tech: ['Wordpress', 'Elementor'],
    status: 'stable',
    color: '#c2afd1',
    link: 'http://blueoceansp.ai/',
    image: '/thumbnails/blueoceans.png',
  },
]
